### ISSUE TITLE
Bug: lots of flickering after the PR to reduce flickering, when a terminal window has a winbar

### ISSUE THREAD

**Issue by folke** [nvim-lualine/lualine.nvim#1323]
### Repro

```lua
vim.cmd("botright 20 split")
vim.cmd.terminal()
vim.keymap.set("t", "<esc><esc>", "<C-\\><C-n>")
vim.opt_local.winbar = "title: %{b:term_title}" -- this causes the flickering
vim.cmd.startinsert()
```

See this [screenscast](https://streamable.com/2le4c0) for an example. That is using `snacks.terminal`,
but it's the same as in my repro.

**Comment by folke** [comment]
caused by https://github.com/nvim-lualine/lualine.nvim/pull/1316

**Comment by tristan957** [comment]
This still occurs for me in fugitive windows.

**Comment by nickvonkaenel** [comment]
I'm getting flickering when loading into alpha with the recent updates too

**Comment by shadmansaleh** [comment]
Should be fixed in 70fef2406909e6a7beaa98d529c8a8f7183dab9e

**Comment by shadmansaleh** [comment]
@nickvonkaenel can you please open a separate issue for alpha

**Comment by nickvonkaenel** [comment]
> @nickvonkaenel can you check if alpha flicker still exists. if it does open a separate issue on that.

I just checked. The flicker is improved but still exists compared to before where it was non-existent. Before your latest change I could see the default nvim opening screen briefly but now I am just seeing lualine appear briefly before disappearing due to the filetype ignore settings. I can open an issue later tonight.

**Comment by folke** [comment]
Awesome, can confirm the flickering in the terminal is gone. Thanks!!
And all good here :)

**Comment by shadmansaleh** [comment]
@nickvonkaenel check out if 2a5bae925481f999263d6f5ed8361baef8df4f83 fixed the alpha issue you were having.

**Comment by nickvonkaenel** [comment]
> @nickvonkaenel check out if [2a5bae9](https://github.com/nvim-lualine/lualine.nvim/commit/2a5bae925481f999263d6f5ed8361baef8df4f83) fixed the alpha issue you were having.

That fixed it! Thanks

**Comment by bmichotte** [comment]
I still have the flickering issue as soon as I update lualine to the last commits

https://share.cleanshot.com/DwZrrB7W

**Comment by tristan957** [comment]
An easy way for me to reproduce the flickering is with entering command mode via pressing `:`
