### ISSUE TITLE
Bug: Intro screen cleared immediately

### ISSUE THREAD

**Issue by fitrh** [nvim-lualine/lualine.nvim#773]
### Self Checks

- [x] I'm using the latest lualine.
- [x] I didn't find the issue in exsisting issues or prs.

### How to reproduce the problem

- Run neovim with `--clean` option and load lualine
  ```sh
  nvim --clean \
      -c 'packadd lualine.nvim' \
      -c 'lua require("lualine").setup()'
  ```

### Expected behaviour

Neovim opens with an intro screen

### Actual behaviour

The intro screen cleared immediately

### Minimal config to reproduce the issue

No need for minimal config as the reproduction steps mimic a fresh install
of neovim and skip all initialization step

**Comment by shadmansaleh** [comment]
https://github.com/nvim-lualine/lualine.nvim/issues/259#issuecomment-1200083574

Intro gets cleared on first redraw and setting stl in scheduled function seems to act as a redraw.

**Comment by shadmansaleh** [comment]
I've asked the nvim devs . It's a bug in neovim.

**Comment by jacobsonryan** [comment]
Any updates?

**Comment by shadmansaleh** [comment]
> Any updates?

**Comment by fitrh** [comment]
This was fixed on my latest build (7fc5f66)

**Comment by yannjor** [comment]
Still having the same problem, with the latest lualine and neovim v0.9.0-dev-3-gafb7efb373.

**Comment by fitrh** [comment]
@yannjor can you reproduce it using the minimal config?

**Comment by yannjor** [comment]
Yes, I removed everything from my config leaving only `require("lualine").setup()` and still the same.

**Comment by fitrh** [comment]
I can confirm it, it's weird, my full config does not have the issue but the minimal config has

**Comment by Tony-Sol** [comment]
Same here

**Comment by ryanburda** [comment]
[Disabling separators](https://github.com/nvim-lualine/lualine.nvim#disabling-separators) keeps the intro screen up for me. @fitrh @Tony-Sol any chance this explains the difference between your full config and the minimal config?

**Comment by Tony-Sol** [comment]
Solution with empty separators is not working for me - it skips intro screen even with empty `require('lualine').setup {}`

Full config here: https://github.com/Tony-Sol/.config/blob/master/nvim/lua/configs.lua

**Comment by sahibalejandro** [comment]
In my case startup screen is displayed by only set `options.section_separators = ''`

**Comment by wardw** [comment]
I noticed it works if you call `require('lualine').setup` from `after/plugin`.

**Comment by jsatk** [comment]
`options.section_separators = ''` also works for me. But of course I don't want that. I like having separators.

**Comment by lalitmeeq** [comment]
I was not sure what was causing this issue. I came here looking for something else but found this issue. Its happening to me and I was trying to fix it but nothing mentioned above worked for me.

**Comment by CFiggers** [comment]
Also experiencing this issue.

**Comment by jives** [comment]
Same here. However, Neovide 0.12.1 (on Windows 10) doesn't show this behavior, independent of the `no-multigrid` setting.
![image](https://github.com/nvim-lualine/lualine.nvim/assets/1925184/70d528cc-c3ea-4a10-a021-7c73ab91fa63)

To my understanding, Neovide is just a "client"; is it possible that the issue could be patched outside of nvim upstream after all?
